export type { Ref } from "./types/ref.type";
export * from "./timestamp.interface";
export * from "./user.interface";
export * from "./session.interface";
export * from "./board.interface";
export * from "./memberRole.interface";
export * from "./associationMember.interface";
export * from "./chapter.interface";
export * from "./center.interface";
export * from "./galery.interface";
export * from "./image.interface";
export * from "./school.interface";
export * from "./partner.interface";